version: "1"
services:
  django:
    image: ubuntu:14.04
    
  postgresql:
    image: postgres:9.4
    expose:
      - "5432"
    volumes:
      - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'sesame'
      POSTGRES_DB: 'example'
     
registries: {}
