
- kube_service:
    service_name: static
    ports:
    - name: port-80
      port: 80
      targetPort: 8080
    selector:
      app: example
      service: static
    type: LoadBalancer
  register: output

- debug: var=output
  when: playbook_debug

- kube_service:
    service_name: postgresql
    ports:
    - name: port-5432
      port: 5432
      targetPort: 5432
    selector:
      app: example
      service: postgresql
  register: output

- debug: var=output
  when: playbook_debug

- kube_service:
    service_name: django
    ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
    selector:
      app: example
      service: django
  register: output

- debug: var=output
  when: playbook_debug
